app:
  database:
    type: mysql
    user: root
    password: root
    dbName: seckill
    address: 127.0.0.1:23306
    maxIdle: 10
    maxOpen: 10
  redis:
    address: 127.0.0.1:6379
    network: tcp
    password: 123456
    maxIdle: 10
    maxActive: 30
    idleTimeout: 200