version: "2"
services:
  mysql-service:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: 'no'
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "dev"
      MYSQL_USER: "developer"
      MYSQL_PASSWORD: "123456"
  redis-service:
    image: redis
    command: redis-server --requirepass 123456
    ports:
      - "6379:6379"
    restart: 'no'
  seckill:
    restart: 'no'
    build: ./
    ports:
      - "8000:8000"
    links:
      - mysql-service:mysql
      - redis-service:redis
